"""empty message

Revision ID: 017bc688b20f
Revises: 270947efbfd8
Create Date: 2019-03-15 19:17:26.979166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017bc688b20f'
down_revision = '270947efbfd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('movie_10', sa.String(), nullable=True))
    op.add_column('results', sa.Column('movie_10_results', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('movie_11', sa.String(), nullable=True))
    op.add_column('results', sa.Column('movie_11_results', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('movie_12', sa.String(), nullable=True))
    op.add_column('results', sa.Column('movie_12_results', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('movie_13', sa.String(), nullable=True))
    op.add_column('results', sa.Column('movie_13_results', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('movie_14', sa.String(), nullable=True))
    op.add_column('results', sa.Column('movie_14_results', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('movie_15', sa.String(), nullable=True))
    op.add_column('results', sa.Column('movie_15_results', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('movie_16', sa.String(), nullable=True))
    op.add_column('results', sa.Column('movie_16_results', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('movie_17', sa.String(), nullable=True))
    op.add_column('results', sa.Column('movie_17_results', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('movie_18', sa.String(), nullable=True))
    op.add_column('results', sa.Column('movie_18_results', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('movie_19', sa.String(), nullable=True))
    op.add_column('results', sa.Column('movie_19_results', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('movie_2', sa.String(), nullable=True))
    op.add_column('results', sa.Column('movie_20', sa.String(), nullable=True))
    op.add_column('results', sa.Column('movie_20_results', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('movie_2_results', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('movie_3', sa.String(), nullable=True))
    op.add_column('results', sa.Column('movie_3_results', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('movie_4', sa.String(), nullable=True))
    op.add_column('results', sa.Column('movie_4_results', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('movie_5', sa.String(), nullable=True))
    op.add_column('results', sa.Column('movie_5_results', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('movie_6', sa.String(), nullable=True))
    op.add_column('results', sa.Column('movie_6_results', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('movie_7', sa.String(), nullable=True))
    op.add_column('results', sa.Column('movie_7_results', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('movie_8', sa.String(), nullable=True))
    op.add_column('results', sa.Column('movie_8_results', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('movie_9', sa.String(), nullable=True))
    op.add_column('results', sa.Column('movie_9_results', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'movie_9_results')
    op.drop_column('results', 'movie_9')
    op.drop_column('results', 'movie_8_results')
    op.drop_column('results', 'movie_8')
    op.drop_column('results', 'movie_7_results')
    op.drop_column('results', 'movie_7')
    op.drop_column('results', 'movie_6_results')
    op.drop_column('results', 'movie_6')
    op.drop_column('results', 'movie_5_results')
    op.drop_column('results', 'movie_5')
    op.drop_column('results', 'movie_4_results')
    op.drop_column('results', 'movie_4')
    op.drop_column('results', 'movie_3_results')
    op.drop_column('results', 'movie_3')
    op.drop_column('results', 'movie_2_results')
    op.drop_column('results', 'movie_20_results')
    op.drop_column('results', 'movie_20')
    op.drop_column('results', 'movie_2')
    op.drop_column('results', 'movie_19_results')
    op.drop_column('results', 'movie_19')
    op.drop_column('results', 'movie_18_results')
    op.drop_column('results', 'movie_18')
    op.drop_column('results', 'movie_17_results')
    op.drop_column('results', 'movie_17')
    op.drop_column('results', 'movie_16_results')
    op.drop_column('results', 'movie_16')
    op.drop_column('results', 'movie_15_results')
    op.drop_column('results', 'movie_15')
    op.drop_column('results', 'movie_14_results')
    op.drop_column('results', 'movie_14')
    op.drop_column('results', 'movie_13_results')
    op.drop_column('results', 'movie_13')
    op.drop_column('results', 'movie_12_results')
    op.drop_column('results', 'movie_12')
    op.drop_column('results', 'movie_11_results')
    op.drop_column('results', 'movie_11')
    op.drop_column('results', 'movie_10_results')
    op.drop_column('results', 'movie_10')
    # ### end Alembic commands ###
