"""empty message

Revision ID: 12f7b3483793
Revises: 68e4c3a924d1
Create Date: 2019-03-04 18:57:27.404335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12f7b3483793'
down_revision = '68e4c3a924d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datechanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio', sa.String(), nullable=False),
    sa.Column('dateOfChange', sa.Date(), nullable=False),
    sa.Column('oldDate', sa.Date(), nullable=True),
    sa.Column('newDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datechanges')
    # ### end Alembic commands ###
