"""empty message

Revision ID: 1400123fbbce
Revises: 44df63277d7c
Create Date: 2019-03-02 17:57:32.178477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1400123fbbce'
down_revision = '44df63277d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boxoffice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currentDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('cash', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studio')
    op.drop_table('boxoffice')
    # ### end Alembic commands ###
