"""empty message

Revision ID: 14bab1e10081
Revises: 9e0bb998a669
Create Date: 2019-03-04 20:40:53.254192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14bab1e10081'
down_revision = '9e0bb998a669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moviechanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie', sa.String(), nullable=False),
    sa.Column('dateOfChange', sa.Date(), nullable=False),
    sa.Column('created', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moviechanges')
    # ### end Alembic commands ###
