"""empty message

Revision ID: 1e0b94c8ec3c
Revises: 017bc688b20f
Create Date: 2019-03-24 20:18:05.479063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0b94c8ec3c'
down_revision = '017bc688b20f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cash', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
