"""empty message

Revision ID: 2695d551af1d
Revises: 4e00adb79c78
Create Date: 2019-05-25 19:46:20.439248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2695d551af1d'
down_revision = '4e00adb79c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'china_gross',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movies', 'dom_gross',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movies', 'int_gross',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'int_gross',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movies', 'dom_gross',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movies', 'china_gross',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
