"""empty message

Revision ID: 28d5fdd3d25b
Revises: e0bee2ce3531
Create Date: 2019-03-12 22:01:33.861861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d5fdd3d25b'
down_revision = 'e0bee2ce3531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cash', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='studio_pkey')
    )
    # ### end Alembic commands ###
