"""empty message

Revision ID: 33b3273b47f9
Revises: d709caf1aef0
Create Date: 2019-05-25 19:42:02.513502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b3273b47f9'
down_revision = 'd709caf1aef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'china_gross')
    op.drop_column('movies', 'dom_gross')
    op.drop_column('movies', 'int_gross')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('int_gross', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('movies', sa.Column('dom_gross', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('movies', sa.Column('china_gross', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
