"""empty message

Revision ID: 44df63277d7c
Revises: 
Create Date: 2019-03-02 17:34:16.329228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44df63277d7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('budget_spent', sa.Integer(), nullable=False),
    sa.Column('advertising', sa.Integer(), nullable=False),
    sa.Column('advertising_spent', sa.Integer(), nullable=False),
    sa.Column('poster', sa.String(), nullable=True),
    sa.Column('dom_gross', sa.String(), nullable=False),
    sa.Column('int_gross', sa.String(), nullable=False),
    sa.Column('china_gross', sa.String(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('production_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
