"""empty message

Revision ID: 9b1a122c9361
Revises: 12f7b3483793
Create Date: 2019-03-04 19:02:51.579404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1a122c9361'
down_revision = '12f7b3483793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datechanges', sa.Column('movie', sa.String(), nullable=False))
    op.drop_column('datechanges', 'studio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datechanges', sa.Column('studio', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('datechanges', 'movie')
    # ### end Alembic commands ###
