"""empty message

Revision ID: 9e0bb998a669
Revises: 9b1a122c9361
Create Date: 2019-03-04 20:28:44.076447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0bb998a669'
down_revision = '9b1a122c9361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datechanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie', sa.String(), nullable=False),
    sa.Column('dateOfChange', sa.Date(), nullable=False),
    sa.Column('oldDate', sa.Date(), nullable=True),
    sa.Column('newDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datechanges')
    # ### end Alembic commands ###
