"""empty message

Revision ID: a3f150066e63
Revises: 2695d551af1d
Create Date: 2019-06-22 10:10:28.953602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f150066e63'
down_revision = '2695d551af1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('trailers', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'trailers')
    # ### end Alembic commands ###
