"""empty message

Revision ID: cec3e0079d37
Revises: 1400123fbbce
Create Date: 2019-03-02 18:11:44.906584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec3e0079d37'
down_revision = '1400123fbbce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('studio', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'studio')
    # ### end Alembic commands ###
