"""empty message

Revision ID: d32519a30249
Revises: 14bab1e10081
Create Date: 2019-03-04 20:52:31.514830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd32519a30249'
down_revision = '14bab1e10081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datechanges', sa.Column('studio', sa.String(), nullable=False))
    op.add_column('moviechanges', sa.Column('studio', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moviechanges', 'studio')
    op.drop_column('datechanges', 'studio')
    # ### end Alembic commands ###
