"""empty message

Revision ID: d709caf1aef0
Revises: 0682670d8b62
Create Date: 2019-05-25 19:21:03.965915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd709caf1aef0'
down_revision = '0682670d8b62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('movie', sa.String(), nullable=True))
    op.add_column('results', sa.Column('movie_gross', sa.Float(), nullable=True))
    op.drop_column('results', 'movie_10_results')
    op.drop_column('results', 'movie_2_results')
    op.drop_column('results', 'movie_15_results')
    op.drop_column('results', 'movie_17_results')
    op.drop_column('results', 'movie_11')
    op.drop_column('results', 'movie_12_results')
    op.drop_column('results', 'movie_1_results')
    op.drop_column('results', 'movie_7_results')
    op.drop_column('results', 'movie_18')
    op.drop_column('results', 'movie_12')
    op.drop_column('results', 'movie_14_results')
    op.drop_column('results', 'movie_4')
    op.drop_column('results', 'movie_5_results')
    op.drop_column('results', 'movie_4_results')
    op.drop_column('results', 'movie_3')
    op.drop_column('results', 'movie_11_results')
    op.drop_column('results', 'movie_17')
    op.drop_column('results', 'movie_6')
    op.drop_column('results', 'movie_6_results')
    op.drop_column('results', 'movie_10')
    op.drop_column('results', 'movie_20')
    op.drop_column('results', 'movie_16')
    op.drop_column('results', 'movie_19')
    op.drop_column('results', 'movie_8_results')
    op.drop_column('results', 'movie_13')
    op.drop_column('results', 'movie_19_results')
    op.drop_column('results', 'movie_7')
    op.drop_column('results', 'movie_16_results')
    op.drop_column('results', 'movie_1')
    op.drop_column('results', 'movie_20_results')
    op.drop_column('results', 'movie_2')
    op.drop_column('results', 'movie_3_results')
    op.drop_column('results', 'movie_14')
    op.drop_column('results', 'movie_15')
    op.drop_column('results', 'movie_13_results')
    op.drop_column('results', 'movie_9')
    op.drop_column('results', 'movie_18_results')
    op.drop_column('results', 'movie_5')
    op.drop_column('results', 'movie_9_results')
    op.drop_column('results', 'movie_8')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('movie_8', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_9_results', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_5', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_18_results', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_9', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_13_results', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_15', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_14', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_3_results', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_20_results', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_16_results', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_7', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_19_results', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_13', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_8_results', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_19', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_16', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_20', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_10', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_6_results', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_6', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_17', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_11_results', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_4_results', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_5_results', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_4', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_14_results', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_12', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_18', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_7_results', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_1_results', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_12_results', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_11', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_17_results', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_15_results', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_2_results', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('movie_10_results', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('results', 'movie_gross')
    op.drop_column('results', 'movie')
    # ### end Alembic commands ###
