"""empty message

Revision ID: dcd10be589c1
Revises: 
Create Date: 2019-03-05 10:15:46.151841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd10be589c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boxoffice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currentDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datechanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie', sa.String(), nullable=False),
    sa.Column('studio', sa.String(), nullable=False),
    sa.Column('dateOfChange', sa.Date(), nullable=False),
    sa.Column('oldDate', sa.Date(), nullable=True),
    sa.Column('newDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moviechanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie', sa.String(), nullable=False),
    sa.Column('studio', sa.String(), nullable=False),
    sa.Column('dateOfChange', sa.Date(), nullable=False),
    sa.Column('created', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('studio', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('budget_spent', sa.Integer(), nullable=False),
    sa.Column('advertising', sa.Integer(), nullable=False),
    sa.Column('advertising_spent', sa.Integer(), nullable=False),
    sa.Column('poster', sa.String(), nullable=True),
    sa.Column('dom_gross', sa.String(), nullable=False),
    sa.Column('int_gross', sa.String(), nullable=False),
    sa.Column('china_gross', sa.String(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('production_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('cash', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('studio')
    op.drop_table('movies')
    op.drop_table('moviechanges')
    op.drop_table('datechanges')
    op.drop_table('boxoffice')
    op.drop_table('announcements')
    # ### end Alembic commands ###
