"""empty message

Revision ID: f07b1721c394
Revises: dcd10be589c1
Create Date: 2019-03-05 20:52:55.171996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07b1721c394'
down_revision = 'dcd10be589c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('studio', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'studio')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
